services:
  - type: web
    name: video-merger-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
